export const SEL = {
  testid: {
    emptyData: 'empty-data',
    skeleton: 'skeleton',
    notificationBadge: 'notification-badge',
    stepper: 'stepper',
    profilePhoto: 'profile-photo',
    profileName: 'profile-name',
    profileEmail: 'profile-email',
    profilePhone: 'profile-phone',
    userName: 'user-name',
    userProfile: 'user-profile',
    roleSelect: 'role-select',
    filterRole: 'filter-role',
    filterStatus: 'filter-status',
    workspaceCard: 'workspace-card',
    companyName: 'company-name',
    navCard: 'nav-card',
    passwordStrength: 'password-strength',
    businessTypeSelect: 'business-type-select',
    stepIndicator: 'step-indicator',
    infiniteScrollTrigger: 'infinite-scroll-trigger',
    moduleCard: 'module-card',
    quickAction: 'quick-action',
    welcomeSection: 'welcome-section',
    languageSwitcher: 'language-switcher',
    profileDropdown: 'profile-dropdown',
    pageTitle: 'page-title',
    sidebar: 'sidebar',
    navbar: 'navbar',
    notificationItem: 'notification-item',
    notificationBody: 'notification-body',
    filterButton: 'filter-button',
    otpInput: 'otp-input',
  },
  button: {
    tambah: /tambah|buat|create/i,
    simpan: /simpan|save/i,
    batal: /batal|cancel/i,
    lanjut: /lanjut|next|selanjutnya/i,
    kembali: /kembali|back/i,
  },
  toast: {
    root: '[role="status"]',
    message: '[data-toast-message], [role="status"] p',
  },
  modal: {
    root: '[role="dialog"]',
    title: '[role="dialog"] [role="heading"]',
  },
  state: {
    error: '[data-helper-text], [data-error], .text-app-pr-info-critical-600, [aria-invalid="true"]',
    skeleton: '[data-testid="skeleton"]',
  },
  indicator: {
    passwordSecurity: '[data-input-group-password-security="true"]',
  },
} as const;
